name: Playwright Tests

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

  schedule:
    - cron: '0 1 * * *'   # ทุกวัน 08:00 น. (ประเทศไทย)

  workflow_dispatch:
    inputs:
      browser:
        description: "Select Browser"
        required: true
        default: "chromium"
        type: choice
        options:
          - chromium
          - firefox
          - webkit

      test_suite:
        description: "Select Test Suite"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - webform

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then

            echo "Browser : ${{ github.event.inputs.browser }}"
            echo "Suite   : ${{ github.event.inputs.test_suite }}"

            if [ "${{ github.event.inputs.test_suite }}" = "webform" ]; then
              npx playwright test tests/webform.spec.ts --project=${{ github.event.inputs.browser }}
            else
              npx playwright test --project=${{ github.event.inputs.browser }}
            fi

          else
            echo "Running all tests on chromium"
            npx playwright test --project=chromium
          fi

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
          retention-days: 30